[package]
name = "webauthn-rp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core WebAuthn
webauthn-rs = { version = "0.5", features = ["danger-allow-state-serialisation"] }

# Web framework
actix-web = "4.9"
actix-cors = "0.7"
actix-rt = "2.10"

# Database
diesel = { version = "2.1", features = ["postgres", "uuid", "chrono", "serde_json"] }
diesel_migrations = "2.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities
uuid = { version = "1.10", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.22"
rand = "0.8"
thiserror = "1.0"
anyhow = "1.0"

# Async
tokio = { version = "1.40", features = ["full"] }
futures = "0.3"

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# Security
argon2 = "0.5"
aes-gcm = "0.10"

[dev-dependencies]
# Testing framework
tokio-test = "0.4"
actix-test = "0.1"

# Mocking
mockall = "0.13"
wiremock = "0.6"

# Test utilities
tempfile = "3.8"
serial_test = "3.1"
proptest = "1.4"
criterion = { version = "0.5", features = ["html_reports"] }

# Test database
testcontainers = "0.20"
testcontainers-modules = { version = "0.8", features = ["postgres"] }

[features]
default = []
test-utils = []

[[bench]]
name = "registration_bench"
harness = false
path = "benches/registration_bench.rs"

[[bench]]
name = "authentication_bench"
harness = false
path = "benches/authentication_bench.rs"