[package]
name = "fido2-conformance-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core WebAuthn functionality
webauthn-rs = "0.5"
webauthn-rs-proto = "0.5"

# Web framework
actix-web = "4.9"
actix-cors = "0.7"
actix-rt = "2.10"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Database
diesel = { version = "2.1", features = ["postgres", "r2d2", "chrono", "uuid"] }
r2d2 = "0.8"

# Security and crypto
base64 = "0.22"
sha2 = "0.10"
rand = "0.8"
uuid = { version = "1.0", features = ["v4", "serde"] }

# Async runtime
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"

# Configuration
config = "0.14"

[dev-dependencies]
# Testing framework
actix-test = "0.1"
mockall = "0.13"
tokio-test = "0.4"
wiremock = "0.6"
testcontainers = "0.20"
proptest = "1.4"
criterion = "0.5"
fake = "2.9"
rstest = "0.21"
serial_test = "3.1"
tempfile = "3.8"

# HTTP client for testing
reqwest = { version = "0.12", features = ["json"] }

# Additional test utilities
pretty_assertions = "1.4"
test-case = "3.3"

[[bin]]
name = "fido2-server"
path = "src/main.rs"

[lib]
name = "fido2_conformance_tests"
path = "src/lib.rs"