[package]
name = "fido-server"
version = "0.1.0"
edition = "2021"
authors = ["FIDO Server Team"]
license = "MIT"
repository = "https://github.com/yourorg/fido-server"
readme = "README.md"

[lib]
name = "fido_server"
path = "src/lib.rs"

[[bin]]
name = "fido-server"
path = "src/main.rs"

[dependencies]
# Core async runtime
tokio = { version = "1.40", features = ["full"] }

# Web framework
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace", "timeout"] }

# WebAuthn implementation
webauthn-rs = "0.5"

# Database
diesel = { version = "2.1", features = ["postgres", "uuid", "chrono", "serde_json", "r2d2"] }
diesel-async = { version = "0.4", features = ["postgres", "bb8"] }
diesel_migrations = "2.1"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# UUID and time
uuid = { version = "1.10", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

# Cryptography and security
base64 = "0.22"
rand = "0.8"
sha2 = "0.10"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Configuration
config = "0.14"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

# HTTP client (for testing)
reqwest = { version = "0.11", features = ["json"] }

# JWT (placeholder for future)
jsonwebtoken = "9.2"

# Rate limiting
governor = "0.6"

# Validation
validator = { version = "0.18", features = ["derive"] }
regex = "1.10"

# Async traits
async-trait = "0.1"

[dev-dependencies]
# Testing framework
tokio-test = "0.4"

# Mocking
mockall = "0.12"
wiremock = "0.5"

# Test utilities
pretty_assertions = "1.4"
proptest = "1.4"
quickcheck = "1.0"

# Test database
tempfile = "3.8"

# Property-based testing
proptest-derive = "0.4"

# Integration testing
testcontainers = "0.15"
testcontainers-modules = { version = "0.3", features = ["postgres"] }

# Security testing
criterion = { version = "0.5", features = ["html_reports"] }

# HTTP testing for integration
axum-test = "15.0"

# Environment variable testing for tests
dotenvy = "0.15"

[features]
default = ["postgres"]
postgres = []
test-utils = []

[[bench]]
name = "webauthn_benchmarks"
harness = false