[package]
name = "fido-server3"
version = "0.1.0"
edition = "2021"
authors = ["FIDO Server Team"]
description = "FIDO2/WebAuthn Relying Party Server implementation in Rust"
license = "MIT"

[dependencies]
# WebAuthn core library
webauthn-rs = { version = "0.5", features = ["danger-allow-state-serialisation"] }

# Async runtime and web framework
tokio = { version = "1.0", features = ["full"] }
axum = { version = "0.7", features = ["json", "headers", "tower-log"] }

# Database and ORM
sqlx = { version = "0.7", features = [
    "postgres", 
    "runtime-tokio-rustls", 
    "uuid", 
    "chrono",
    "migrate"
] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.21"
url = "2.4"

# Logging and tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# HTTP middleware and utilities
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace", "timeout", "limit"] }
hyper = "1.0"

# Security
ring = "0.17"
rand = "0.8"

# Configuration
config = "0.14"
dotenvy = "0.15"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

[dev-dependencies]
tokio-test = "0.4"
reqwest = { version = "0.11", features = ["json"] }
tempfile = "3.8"

[features]
default = ["postgres"]
postgres = []
memory-only = []

[[bin]]
name = "fido-server3"
path = "src/main.rs"