[package]
name = "fido-server"
version = "0.1.0"
edition = "2021"
authors = ["FIDO Server Team"]
license = "MIT"
repository = "https://github.com/yourorg/fido-server"
readme = "README.md"
description = "A FIDO2/WebAuthn conformant server implementation in Rust"
keywords = ["fido", "webauthn", "authentication", "security"]
categories = ["authentication", "web-programming"]

[lib]
name = "fido_server"
path = "src/lib.rs"

[[bin]]
name = "fido-server"
path = "src/main.rs"

[dependencies]
# Web Framework
actix-web = "4.9"
actix-cors = "0.7"
actix-rt = "2.10"

# FIDO/WebAuthn
webauthn-rs = { version = "0.5", features = ["danger-allow-state-serialisation"] }
webauthn-rs-proto = "0.5"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Database
diesel = { version = "2.1", features = ["postgres", "r2d2", "chrono", "uuid"] }
diesel_migrations = "2.1"
r2d2 = "0.8"

# Async
tokio = { version = "1.40", features = ["full"] }
futures = "0.3"
async-trait = "0.1"

# Cryptography
base64 = "0.22"
uuid = { version = "1.10", features = ["v4", "serde"] }
rand = "0.8"
sha2 = "0.10"
url = "2.5"

# Configuration
config = "0.14"
dotenv = "0.15"

# Logging
log = "0.4"
env_logger = "0.11"

# Error Handling
thiserror = "1.0"
anyhow = "1.0"

# Time
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
actix-test = "0.1"
mockall = "0.13"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

# Strict linting configuration
[lints.rust]
unused_must_use = "deny"
unused_imports = "warn"
dead_code = "warn"


