[package]
name = "fido-server"
version = "0.1.0"
edition = "2021"
authors = ["FIDO Server Team"]
license = "MIT"
repository = "https://github.com/yourorg/fido-server"
readme = "README.md"

[lib]
name = "fido_server"
path = "src/lib.rs"

[[bin]]
name = "fido-server"
path = "src/main.rs"

[dependencies]
# Web Framework
actix-web = "4.9"
actix-cors = "0.7"
actix-rt = "2.10"

# FIDO/WebAuthn
webauthn-rs = "0.5"
webauthn-rs-proto = "0.5"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Database
diesel = { version = "2.1", features = ["postgres", "r2d2", "chrono", "uuid"] }
diesel_migrations = "2.1"
r2d2 = "0.8"

# Async
tokio = { version = "1.40", features = ["full"] }
futures = "0.3"

# Cryptography
base64 = "0.22"
uuid = { version = "1.10", features = ["v4", "serde"] }
rand = "0.8"
sha2 = "0.10"

# Configuration
config = "0.14"
dotenv = "0.15"

# Logging
log = "0.4"
env_logger = "0.11"

# Error Handling
thiserror = "1.0"
anyhow = "1.0"

# Time
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
# Testing Framework
actix-test = "0.1"
mockall = "0.13"
tokio-test = "0.4"

# Test Utilities
proptest = "1.5"  # Property-based testing
quickcheck = "1.0"
fake = { version = "2.9", features = ["derive", "chrono", "uuid"] }

# Test Database
testcontainers = "0.16"
testcontainers-modules = { version = "0.4", features = ["postgres"] }

# Security Testing
criterion = "0.5"  # Performance testing
iai = "0.1"        # Benchmarking

# Coverage
tarpaulin = "0.27"

# Additional testing dependencies
hex = "0.4"
serde_cbor = "0.11"
ring = "0.17"  # For cryptographic testing

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

# Strict linting configuration
[lints.rust]
unused_must_use = "deny"
missing_docs = "warn"
unused_imports = "warn"
dead_code = "warn"

[lints.clippy]
all = "deny"
pedantic = "deny"
nursery = "warn"
cargo = "warn"
# Allow some pedantic lints that are too strict
module_name_repetitions = "allow"
missing_errors_doc = "allow"

# Testing profiles
[profile.test]
opt-level = 1
debug = true



[[test]]
name = "webauthn_integration"
path = "tests/integration/webauthn_tests.rs"

[[test]]
name = "security_tests"
path = "tests/security/security_tests.rs"
