[package]
name = "fido2-webauthn-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# Web framework
actix-web = "4.4"
actix-cors = "0.7"
tokio = { version = "1.0", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# WebAuthn
webauthn-rs = "0.5"

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "migrate"] }

# Cryptography & Security
rand = "0.8"
base64 = "0.21"
sha2 = "0.10"
hmac = "0.12"

# Validation
validator = { version = "0.16", features = ["derive"] }
regex = "1.0"

# UUID
uuid = { version = "1.0", features = ["v4", "serde"] }

# Time
chrono = { version = "0.4", features = ["serde"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"
env_logger = "0.10"

# Async
futures = "0.3"
futures-util = "0.3"
async-trait = "0.1"

# Static regex compilation
lazy_static = "1.4"

[dev-dependencies]
# Testing
actix-rt = "2.9"
mockall = "0.11"
tempfile = "3.8"
wiremock = "0.5"
proptest = "1.4"

# Test utilities
pretty_assertions = "1.4"
serial_test = "3.0"

[features]
default = []
test-utils = []