[package]
name = "fido-server"
version = "0.1.0"
edition = "2021"
authors = ["FIDO Server Team"]
license = "MIT"
repository = "https://github.com/yourorg/fido-server"
readme = "README.md"

[lib]
name = "fido_server"
path = "src/lib.rs"

[[bin]]
name = "fido-server"
path = "src/main.rs"

[dependencies]
# Core dependencies
tokio = { version = "1.40", features = ["full"] }
uuid = { version = "1.10", features = ["v4", "serde"] }
base64 = "0.22"
rand = "0.8"
thiserror = "1.0"

[dev-dependencies]
# Testing framework
tokio-test = "0.4"