[package]
name = "fido-server"
version = "0.1.0"
edition = "2021"
authors = ["FIDO Server Team"]
description = "A FIDO2/WebAuthn Relying Party Server built with Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/fido-server/fido-server"

[dependencies]
# WebAuthn
webauthn-rs = "0.13.2"
webauthn-rs-core = "0.13.2"

# Web framework
axum = "0.7.5"
tokio = { version = "1.37.0", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.5.2", features = ["cors", "trace", "compression-full"] }

# Database
sqlx = { version = "0.7.4", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }
uuid = { version = "1.8.0", features = ["v4", "serde"] }
chrono = { version = "0.4.38", features = ["serde"] }

# Serialization
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"

# Error handling
anyhow = "1.0.82"
thiserror = "1.0.58"

# Security
ring = "0.17.8"
base64 = "0.22.0"
rand = "0.8.5"

# Logging
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# Configuration
config = "0.14.0"

# HTTP client for webhooks
reqwest = { version = "0.12.4", features = ["json"] }

# Rate limiting
governor = "0.6.3"

# Validation
validator = { version = "0.18.1", features = ["derive"] }

# Async traits
async-trait = "0.1.77"

[dev-dependencies]
tempfile = "3.10.1"
mockall = "0.12.1"

[[bin]]
name = "fido-server"
path = "src/main.rs"

[lib]
name = "fido_server"
path = "src/lib.rs"