[package]
name = "fido-server"
version = "0.1.0"
edition = "2021"
authors = ["FIDO Server Team"]
license = "MIT"
repository = "https://github.com/yourorg/fido-server"
readme = "README.md"

[lib]
name = "fido_server"
path = "src/lib.rs"

[[bin]]
name = "fido-server"
path = "src/main.rs"

[dependencies]
# Web Framework
actix-web = { version = "4.9", features = ["openssl"] }
actix-cors = "0.7"
actix-rt = "2.10"
actix-multipart = "0.6"

# FIDO/WebAuthn
webauthn-rs = { version = "0.5", features = ["danger-credential-internals"] }
webauthn-rs-proto = "0.5"
url = "2.5"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Database
diesel = { version = "2.1", features = ["postgres", "r2d2", "chrono", "uuid", "serde_json"] }
diesel_migrations = "2.1"
r2d2 = "0.8"

# Async Runtime
tokio = { version = "1.40", features = ["full"] }
futures = "0.3"

# Cryptography & Security
base64 = "0.22"
uuid = { version = "1.10", features = ["v4", "serde"] }
rand = "0.8"
sha2 = "0.10"
hmac = "0.12"
ring = "0.17"
openssl = "0.10"

# Configuration
config = "0.14"
dotenv = "0.15"

# Logging & Monitoring
log = "0.4"
env_logger = "0.11"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
prometheus = { version = "0.13", features = ["process"] }

# Error Handling
thiserror = "1.0"
anyhow = "1.0"

# Time & Date
chrono = { version = "0.4", features = ["serde"] }

# HTTP Client (for attestation verification)
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }

# JWT & Authentication
jsonwebtoken = "9.3"

# Rate Limiting
governor = "0.6"

# Validation
validator = { version = "0.18", features = ["derive"] }

# Caching
redis = { version = "0.25", features = ["tokio-comp"] }

# Additional dependencies
pbkdf2 = "0.12"
hex = "0.4"
num_cpus = "1.16"
lazy_static = "1.4"
regex = "1.11"

[dev-dependencies]
actix-test = "0.1"
mockall = "0.13"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

# Strict linting configuration
[lints.rust]
unused_must_use = "deny"
missing_docs = "warn"
unused_imports = "warn"
dead_code = "warn"

[lints.clippy]
all = "deny"
pedantic = "deny"
nursery = "warn"
cargo = "warn"
# Allow some pedantic lints that are too strict
module_name_repetitions = "allow"
missing_errors_doc = "allow"
