[package]
name = "fido2-webauthn-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# WebAuthn
webauthn-rs = "0.5"
base64 = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Web framework
actix-web = "4.4"
actix-cors = "0.7"
actix-rt = "2.9"
tokio = { version = "1.35", features = ["full"] }

# Database
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "migrate"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

# Security
rand = "0.8"
sha2 = "0.10"
hmac = "0.12"

# Validation
validator = { version = "0.18", features = ["derive"] }
regex = "1.0"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = "0.3"
env_logger = "0.10"

# Configuration
config = "0.14"

# Async traits
async-trait = "0.1"

# Testing
mockall = "0.12"
wiremock = "0.6"
tempfile = "3.8"

# Database
diesel = { version = "2.1", features = ["postgres", "r2d2"] }

# Validation
validator = { version = "0.18", features = ["derive"] }
regex = "1.0"
lazy_static = "1.4"

# HTTP Authentication
actix-web-httpauth = "0.8"

# Testing (dev dependencies only)
[dev-dependencies]
# Additional testing dependencies
proptest = "1.4"
quickcheck = "1.0"
criterion = "0.5"
actix-http = "3.4"
futures = "0.3"

