//! Database module

pub mod connection;
pub mod models;

// Include the schema generated by Diesel
#[allow(clippy::all)]
pub mod schema;

pub use connection::{establish_connection, DbPool};
pub use models::*;
