//! Diesel schema for the database
//! 
//! This file is typically generated by `diesel print-schema > src/schema.rs`
//! but we're creating it manually for this example

table! {
    users (id) {
        id -> Text,
        username -> Text,
        display_name -> Text,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}

table! {
    credentials (id) {
        id -> Text,
        user_id -> Text,
        public_key -> Bytea,
        sign_count -> Int4,
        credential_type -> Text,
        attestation_format -> Text,
        aaguid -> Nullable<Bytea>,
        transports -> Nullable<Text>,
        created_at -> Timestamp,
        updated_at -> Timestamp,
        last_used_at -> Nullable<Timestamp>,
    }
}

table! {
    challenges (id) {
        id -> Text,
        challenge -> Text,
        username -> Nullable<Text>,
        challenge_type -> Text,
        expires_at -> Timestamp,
        created_at -> Timestamp,
    }
}

allow_tables_to_appear_in_same_query!(
    users,
    credentials,
    challenges,
);