//! Database schema generated by Diesel

table! {
    users (id) {
        id -> Uuid,
        username -> Varchar,
        display_name -> Varchar,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}

table! {
    credentials (id) {
        id -> Uuid,
        credential_id -> Bytea,
        user_id -> Uuid,
        public_key -> Jsonb,
        sign_count -> Int4,
        attestation_format -> Varchar,
        attestation_data -> Nullable<Bytea>,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}

table! {
    challenges (id) {
        id -> Uuid,
        challenge -> Varchar,
        user_id -> Uuid,
        challenge_type -> Varchar,
        expires_at -> Timestamp,
        created_at -> Timestamp,
    }
}

joinable!(credentials -> users (user_id));
joinable!(challenges -> users (user_id));

allow_tables_to_appear_in_same_query!(
    users,
    credentials,
    challenges,
);